/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.machine;

import ConnectDB.SQLsever.ConnectDB;
import Control.UpdateMoney;
import Control.UpdatePotation;
import Control.View;
import Produce.SodaMoney.ProdureMoney;
import doan.quangnguyen.sodamaker.Potation;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MrYiYi
 */
public final class Admin extends javax.swing.JFrame {
    private final View view =new View();
    ConnectDB con= new ConnectDB();
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        con.getConnect();
      txtNumber.setText("1");
      txtNumberMoney.setText("1");
      txtNamePotation.setText("Name of Patation");
      txtKeyPotation.setText("key of Potation");
      txtPricePotation.setText("price of Potation");
     updateViewPotation();
     updateViewMoney();
     sumOfMoney();
    } 
    public void sumOfMoney(){
    try {
            ResultSet rs= con.runSql("SELECT SUM(denomination*numberMoney)FROM tbMoney");
           if(rs.next()){
               txtSumOfMoney.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupMoney = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lPotation = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamePotation = new javax.swing.JTextField();
        txtKeyPotation = new javax.swing.JTextField();
        txtPricePotation = new javax.swing.JTextField();
        btnPushPotation = new javax.swing.JButton();
        btnPopPotation = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPotationView = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        p1000 = new javax.swing.JRadioButton();
        p2000 = new javax.swing.JRadioButton();
        p5000 = new javax.swing.JRadioButton();
        p10000 = new javax.swing.JRadioButton();
        p20000 = new javax.swing.JRadioButton();
        p50000 = new javax.swing.JRadioButton();
        c1000 = new javax.swing.JRadioButton();
        c2000 = new javax.swing.JRadioButton();
        c5000 = new javax.swing.JRadioButton();
        btnPush = new javax.swing.JButton();
        btnPop = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNumberMoney = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSumOfMoney = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMoney = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");

        jTabbedPane1.setBackground(new java.awt.Color(240, 0, 240));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(0, 240, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N

        lPotation.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Coco Cola", "2.PepSi", "3.C2", "4.Aquafina", "5.Fanta", "6.Sting", "7.Twister", "8.DR Thanh", "9.Nutri Boots", "10.Latte", "11.Sprite", "12.O long", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lPotation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPotationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lPotation);

        jLabel1.setText("List Potation");

        jLabel3.setFont(new java.awt.Font("VNtimes New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Name Potation");

        jLabel4.setFont(new java.awt.Font("VNtimes New Roman", 1, 14)); // NOI18N
        jLabel4.setText("ID Potation");

        jLabel5.setFont(new java.awt.Font("VNtimes New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Price Potation");

        txtNamePotation.setEnabled(false);
        txtNamePotation.setMinimumSize(new java.awt.Dimension(6, 25));

        txtKeyPotation.setEnabled(false);
        txtKeyPotation.setMinimumSize(new java.awt.Dimension(6, 25));

        txtPricePotation.setMinimumSize(new java.awt.Dimension(6, 25));

        btnPushPotation.setText("Push");
        btnPushPotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushPotationActionPerformed(evt);
            }
        });

        btnPopPotation.setText("Pop");
        btnPopPotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopPotationActionPerformed(evt);
            }
        });

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("VNtimes New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Number");

        txtNumber.setInheritsPopupMenu(true);

        btnExit.setText("EXIT");
        btnExit.setToolTipText("");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tbPotationView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Potation Name", "Potation Price ", "Number"
            }
        ));
        jScrollPane2.setViewportView(tbPotationView);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnPushPotation, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKeyPotation, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(txtNamePotation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPricePotation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnPopPotation, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(btnExit))))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNamePotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKeyPotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPricePotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPushPotation)
                                    .addComponent(btnPopPotation)
                                    .addComponent(jButton3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Potations", new javax.swing.ImageIcon(getClass().getResource("/GUI/machine/icon1.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(240, 200, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        groupMoney.add(p1000);
        p1000.setText("Paper1000");

        groupMoney.add(p2000);
        p2000.setText("Paper2000");

        groupMoney.add(p5000);
        p5000.setText("Paper5000");

        groupMoney.add(p10000);
        p10000.setText("Paper10000");

        groupMoney.add(p20000);
        p20000.setText("Paper20000");

        groupMoney.add(p50000);
        p50000.setText("Paper50000");

        groupMoney.add(c1000);
        c1000.setText("Coin1000");

        groupMoney.add(c2000);
        c2000.setText("Coin2000");

        groupMoney.add(c5000);
        c5000.setText("Coin5000");

        btnPush.setText("Push");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        btnPop.setText("Pop");
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("VNtimes New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Number: ");

        jLabel7.setText("Sum of Money");

        tbMoney.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Denomination", "Bred Money", "Number"
            }
        ));
        jScrollPane3.setViewportView(tbMoney);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(c5000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c2000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c1000))
                            .addGap(77, 77, 77))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(p1000)
                                        .addComponent(p2000)
                                        .addComponent(p5000))
                                    .addGap(75, 75, 75)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(p50000)
                                        .addComponent(p10000)
                                        .addComponent(p20000)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNumberMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPush, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(38, 38, 38)
                            .addComponent(btnPop, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSumOfMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1000)
                    .addComponent(c1000)
                    .addComponent(p10000))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2000)
                    .addComponent(p50000)
                    .addComponent(c2000))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5000)
                    .addComponent(p20000)
                    .addComponent(c5000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumberMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPush, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSumOfMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Money", new javax.swing.ImageIcon(getClass().getResource("/GUI/machine/icon1.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void updateViewPotation(){
      
      DefaultTableModel model=(DefaultTableModel)tbPotationView.getModel();
      model.setRowCount(0);
        try {
            ResultSet rs= con.runSql("select*from tbPotation");
            while(rs.next()){
                String value[] = new String[3];
                value[0] = rs.getString(1);
                value[1]=rs.getString(3);
                value[2]=rs.getString(4);
                model.addRow(value);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
       tbPotationView.setModel(model);
       model.fireTableDataChanged();
    }
    public void updateViewMoney(){
    DefaultTableModel model=(DefaultTableModel)tbMoney.getModel();
      model.setRowCount(0);
        try {
            ResultSet rs= con.runSql("select*from tbMoney");
            while(rs.next()){
                String value[] = new String[3];
                value[0] = rs.getString(1);
                value[1]=rs.getString(2);
                value[2]=rs.getString(10);
                model.addRow(value);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
       tbMoney.setModel(model);
       model.fireTableDataChanged();
    }
    private void lPotationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPotationMouseClicked
        int index =lPotation.getAnchorSelectionIndex()+1;
        int iprice =0 ;
        Potation potation = new Potation();
        String ql="Select price from tbPotation where potationKey="+index ;
        try {
           ResultSet rs=con.runSql(ql);
           if(rs.next()){
           iprice =rs.getInt("price");
          }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Not Connected Database",
            "Error",JOptionPane.ERROR_MESSAGE);
        }
        switch (index) {
                case 1 :{
                    potation.setPotationName("Coca Cola");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);
                    break;
                }
                case 2:{
                    potation.setPotationName("Pepsi");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);
                    break;
                }
                case 3:{
                    potation.setPotationName("C2");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);
                    break;
                }
                case 4:{
                    potation.setPotationName("Aquafina");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);
                    break;
                }
                case 5:{
                    potation.setPotationName("Fanta");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
                case 6:{
                    potation.setPotationName("Sting");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
                case 7:{
                    potation.setPotationName("Twister");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
                case 8:{
                    potation.setPotationName("DR Thanh");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
                case 9:{
                    potation.setPotationName("Nutri Boots");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
                case 10:{
                    potation.setPotationName("Latte");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
                case 11:{
                    potation.setPotationName("Sprite");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
                case 12:{
                    potation.setPotationName("O long");
                    potation.setPotationKey(index);
                    potation.setPrice(iprice);break;
                }
        }
      txtNamePotation.setText(potation.getPotationName());
      
      txtKeyPotation.setText(String.valueOf(potation.getPotationKey()));
      txtPricePotation.setText(String.valueOf(potation.getPrice()));
    }//GEN-LAST:event_lPotationMouseClicked

    private void btnPushPotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushPotationActionPerformed
   
     UpdatePotation potation = new UpdatePotation();
     try{
     int iUpdate= potation.runUpdate("pushPotation", txtNumber.getText(),txtNamePotation.getText(),txtKeyPotation.getText(),txtPricePotation.getText());
     this.mess(iUpdate-Integer.parseInt(txtNumber.getText())+1,iUpdate);
     }catch (java.lang.NumberFormatException e){
     JOptionPane.showMessageDialog(this, e.getMessage(),
     "ERROR",JOptionPane.ERROR_MESSAGE);
     }
      try {
            view.setPotation();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
   updateViewPotation();
    }//GEN-LAST:event_btnPushPotationActionPerformed

    private void btnPopPotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopPotationActionPerformed
        UpdatePotation potation = new UpdatePotation();
        try{
        int iUpdate= potation.runUpdate("popPotation", txtNumber.getText(),txtNamePotation.getText(),txtKeyPotation.getText(),txtPricePotation.getText());
        this.mess(iUpdate-Integer.parseInt(txtNumber.getText())+1,iUpdate);
        }catch (java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, e.getMessage(),
            "ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
        updateViewPotation();
    }//GEN-LAST:event_btnPopPotationActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         UpdatePotation potation = new UpdatePotation();
        try{
        int iUpdate= potation.runUpdate("updatePotation", txtNumber.getText(),txtNamePotation.getText(),txtKeyPotation.getText(),txtPricePotation.getText());
        JOptionPane.showMessageDialog(this, "Success",
            "ERROR",JOptionPane.INFORMATION_MESSAGE);
        }catch (java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, e.getMessage(),
            "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        updateViewPotation();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        UpdateMoney money =new UpdateMoney();
        ProdureMoney m = new ProdureMoney();
        int i=2;
        if (groupMoney.getSelection()==p1000.getModel()){
             System.out.print(p1000.getModel());
             m.setPaper1000();
         i= money.runUpdateMoney("updateMoney",m.getPaper1000(),txtNumberMoney.getText());
        }
        if (groupMoney.getSelection()==p2000.getModel()){
              
             m.setPaper2000();
           i=money.runUpdateMoney("updateMoney",m.getPaper2000(),txtNumberMoney.getText());
        }
        if (groupMoney.getSelection()==p5000.getModel()){
            
             m.setPaper5000();
             
             System.out.print(m.getPaper5000().getDenominations());
           i=money.runUpdateMoney("updateMoney",m.getPaper5000(),txtNumberMoney.getText());
        }
        if (groupMoney.getSelection()==p10000.getModel()){
             
             m.setPaper10000();
          i=money.runUpdateMoney("updateMoney",m.getPaper10000(),txtNumberMoney.getText());
        }
        if (groupMoney.getSelection()==p20000.getModel()){
            
             m.setPaper20000();
           i=(money.runUpdateMoney("updateMoney",m.getPaper20000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==p50000.getModel()){
             
              m.setPaper50000();
          i=(money.runUpdateMoney("updateMoney",m.getPaper50000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==c1000.getModel()){
             
              m.setCoin1000();
          i=(money.runUpdateMoney("updateMoney",m.getCoin1000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==c2000.getModel()){
           
             m.setCoin2000();
          i=(money.runUpdateMoney("updateMoney",m.getCoin2000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==c5000.getModel()){
            
             m.setCoin5000();
          i=(money.runUpdateMoney("updateMoney",m.getCoin5000(),txtNumberMoney.getText()));
        }
        try{
        this.mess(i-Integer.parseInt(txtNumberMoney.getText())+1,i);
        }catch(java.lang.NumberFormatException e){
           JOptionPane.showMessageDialog(this, e.getMessage(),
            "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        updateViewMoney();
        sumOfMoney();
    }//GEN-LAST:event_btnPushActionPerformed
public void mess(int status,int number){
        if (status <=0){
            JOptionPane.showMessageDialog(this,"Action success with "+String.valueOf(number)+" Object",
            "Error",JOptionPane.ERROR_MESSAGE);
        }
        else 
            JOptionPane.showMessageDialog(this,"Action success with "+String.valueOf(number)+" Object",
            "Success",JOptionPane.INFORMATION_MESSAGE);
}
    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed
        UpdateMoney money =new UpdateMoney();
        ProdureMoney m = new ProdureMoney();
        int i =2 ;
        if (groupMoney.getSelection()==p1000.getModel()){
             
             m.setPaper1000();
          i=(money.runUpdateMoney("popMoney",m.getPaper1000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==p2000.getModel()){
            
             m.setPaper2000();
           i=(money.runUpdateMoney("popMoney",m.getPaper2000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==p5000.getModel()){
             
             m.setPaper5000();
          i=(money.runUpdateMoney("popMoney",m.getPaper5000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==p10000.getModel()){
             
             m.setPaper10000();
           i=(money.runUpdateMoney("popMoney",m.getPaper10000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==p20000.getModel()){
            
             m.setPaper20000();
           i=(money.runUpdateMoney("popMoney",m.getPaper20000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==p50000.getModel()){
            
              m.setPaper50000();
           i=(money.runUpdateMoney("popMoney",m.getPaper50000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==c1000.getModel()){
             
              m.setCoin1000();
           i=(money.runUpdateMoney("popMoney",m.getCoin1000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==c2000.getModel()){
           
             m.setCoin2000();
           i=(money.runUpdateMoney("popMoney",m.getCoin2000(),txtNumberMoney.getText()));
        }
        if (groupMoney.getSelection()==c5000.getModel()){
             
             m.setCoin5000();
           i=(money.runUpdateMoney("popMoney",m.getCoin5000(),txtNumberMoney.getText()));
        }
        try{
            this.mess(i-Integer.parseInt(txtNumberMoney.getText())+1,i);
        }catch(java.lang.NumberFormatException e){
                JOptionPane.showMessageDialog(this, e.getMessage(),
                 "ERROR",JOptionPane.ERROR_MESSAGE);
             }
        updateViewMoney();
        sumOfMoney();
    }//GEN-LAST:event_btnPopActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPopPotation;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnPushPotation;
    private javax.swing.JRadioButton c1000;
    private javax.swing.JRadioButton c2000;
    private javax.swing.JRadioButton c5000;
    private javax.swing.ButtonGroup groupMoney;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lPotation;
    private javax.swing.JRadioButton p1000;
    private javax.swing.JRadioButton p10000;
    private javax.swing.JRadioButton p2000;
    private javax.swing.JRadioButton p20000;
    private javax.swing.JRadioButton p5000;
    private javax.swing.JRadioButton p50000;
    private javax.swing.JTable tbMoney;
    private javax.swing.JTable tbPotationView;
    private javax.swing.JTextField txtKeyPotation;
    private javax.swing.JTextField txtNamePotation;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtNumberMoney;
    private javax.swing.JTextField txtPricePotation;
    private javax.swing.JTextField txtSumOfMoney;
    // End of variables declaration//GEN-END:variables
}
